### ISSUE TITLE
不能完成点歌操作

### ISSUE THREAD

**Issue by evlic** [maxesisn/nonebot_plugin_songpicker2#3]
nonebot | Running matcher <Matcher from nonebot_plugin_songpicker2, type=message, priority=0, temp=True> failed.
Traceback (most recent call last):
  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nonebot/__init__.py", line 300, in run
    get_driver().run(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 232, in run
    uvicorn.run(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/uvicorn/main.py", line 447, in run
    server.run()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/uvicorn/server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nonebot/message.py", line 158, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/home/ubuntu/.local/lib/python3.8/site-packages/nonebot/message.py", line 207, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nonebot/matcher.py", line 742, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nonebot/matcher.py", line 709, in simple_run
    await handler(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 76, in __call__
    return await self.call(**values)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nonebot_plugin_songpicker2/__init__.py", line 40, in handle_songNum
    songNum = int(state["songNum"])
TypeError: int() argument must be a string, a bytes-like object or a number, not 'Message'

**Comment by maxesisn** [comment]
fixed in https://github.com/maxesisn/nonebot_plugin_songpicker2/commit/2759e38468edc230a13fba6329e83a7fbecb4058

请升级插件至`0.1.6`版本
